---
- name: artisan config:cache
  shell: chdir={{ ansistrano_release_path.stdout }}
    {{ php_path }} artisan config:cache

- name: artisan cache:clear
  shell: chdir={{ ansistrano_release_path.stdout }}
    {{ php_path }} artisan cache:clear

- name: artisan view:clear
  shell: chdir={{ ansistrano_release_path.stdout }}
    {{ php_path }} artisan view:clear

#- name: artisan optimize
#  shell: chdir={{ ansistrano_release_path.stdout }}
#    {{ php_path }} artisan optimize

#- name: artisan route:cache
#  shell: chdir={{ ansistrano_release_path.stdout }}
#    {{ php_path }} artisan route:cache
